# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  build:
    name: "vgo-tools"
    arch: "amd64"
    system: "linux"
    path: "temp"
# ,darwin,windows
