name: Build Release
on:
  push:
    tags:
      - v*
env:
  TZ: Asia/Shanghai

jobs:
  build:
    name: Build And Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "./go.mod"
      - name: install dependencies and set env.BIN_NAME
        run: |
          go version
          make cli 
          gf version
          echo ${{github.ref}}
          pwd
      - name: Build CLI Binary For All Platform
        run: |
          pwd
          go work init
          go work use -r .
          cd vgo-tools
          go mod tidy
          make pack.template-simple
          gf build

      - name: Move Files Before Release
        run: |
          pwd
          cd vgo-tools/temp
          ls
          for OS_DIR in */; do
            # 获取操作系统目录名（去掉末尾的斜杠）
            OS=${OS_DIR%/}

            # 循环遍历每个操作系统目录中的文件
            for FILE in "$OS_DIR"*; do
              # 构建目标文件名，包括操作系统名称
              if [[ $OS =~ 'windows' ]]; then
                  # 如果操作系统名称包含 'windows'，则添加 '.exe' 后缀
                  TARGET_FILE="vgo-tools_${OS}.exe"
              else
                  # 否则，不添加后缀
                  TARGET_FILE="vgo-tools_${OS}"
              fi
              
              # 将文件移动到目标文件名，并删除操作系统目录
              mv "$FILE" "$TARGET_FILE" && rm -rf "$OS_DIR"
            done
          done
          pwd
          ls

      - name: Create Github Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Vgo Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["vgo-tools/temp/vgo-tools_*"]'
